version: '3'
services:
  db:
    build:
      dockerfile: .dockerfile
      context: ./src/database/
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - ./src/database/db:/let/lib/mysql
      - ./src/database/scripts:/docker-entrypoint-initdb.d
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
